# Generated by Django 4.0.5 on 2022-08-18 09:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tour_name', models.CharField(max_length=200)),
                ('city_name', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('duration', models.IntegerField()),
                ('price', models.IntegerField()),
                ('body', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
